### ISSUE TITLE
Use markdown syntax for table

### ISSUE THREAD

**Issue by pelikhan** [microsoft/rise4fun#31]
Avoid inline html as possible

Use (dreaded) markdown syntax for tables

**Comment by NikolajBjorner** [comment]
Is this a style-cop bug?
Table was not created fresh but copied. It was handled as legal input, what did it break?
I have followed the ask. Some <tt> markers left, but they also don't obstruct functionality.

**Comment by pelikhan** [comment]
A general recommendation but you can also dismiss it.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
