### ISSUE TITLE
React Component 

### ISSUE THREAD

**Issue by ayanamonr** [microsoft/rise4fun#7]
- [x] renders z3 source on output

**Comment by rlisahuang** [comment]
Brain dump for resources re: parsing z3 snippets to React components:
- https://docusaurus.io/docs/markdown-features/plugins
- https://github.com/facebook/docusaurus/blob/main/website/src/remark/configTabs.mjs

**Comment by rlisahuang** [comment]
- [ ] use MUI to polish the front-end
